// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0eDCSl_CpvMYvuD0iHR4gALudOjfJjaU',
    appId: '1:445319617982:web:7cffc45cd122234a7f6def',
    messagingSenderId: '445319617982',
    projectId: 'mirc-chat',
    authDomain: 'mirc-chat.firebaseapp.com',
    storageBucket: 'mirc-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUjIc4OrLp66c9A-L-K1o1eF0etybD6bI',
    appId: '1:445319617982:android:ddccaf4557acb2c37f6def',
    messagingSenderId: '445319617982',
    projectId: 'mirc-chat',
    storageBucket: 'mirc-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJVQz_eLuMNurGlleVYWOSaXuiA9biPaI',
    appId: '1:445319617982:ios:2a166ece9afe594e7f6def',
    messagingSenderId: '445319617982',
    projectId: 'mirc-chat',
    storageBucket: 'mirc-chat.appspot.com',
    iosClientId: '445319617982-j6kc6gm4rki0ncqb08bg4q1mttblqnij.apps.googleusercontent.com',
    iosBundleId: 'com.example.mircChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJVQz_eLuMNurGlleVYWOSaXuiA9biPaI',
    appId: '1:445319617982:ios:2a166ece9afe594e7f6def',
    messagingSenderId: '445319617982',
    projectId: 'mirc-chat',
    storageBucket: 'mirc-chat.appspot.com',
    iosClientId: '445319617982-j6kc6gm4rki0ncqb08bg4q1mttblqnij.apps.googleusercontent.com',
    iosBundleId: 'com.example.mircChat',
  );
}
